services:
  nginx:
    image: tcrean15/geodjango_nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - awm_django_app
      - frontend
    networks:
      - awm2024
    stop_grace_period: 1m
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  frontend:
    image: tcrean15/drinking_game_frontend:latest
    expose:
      - "5173"
    networks:
      - awm2024
    environment:
      - VITE_API_URL=https://awm1.uksouth.cloudapp.azure.com/api
    restart: unless-stopped
    stop_grace_period: 1m

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - awm2024
    restart: unless-stopped
    stop_grace_period: 1m

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot 
             --email c21416014@mytudublin.ie --agree-tos --no-eff-email 
             -d awm1.uksouth.cloudapp.azure.com
    depends_on:
      - nginx

  postgis:
    image: postgis/postgis:15-3.3
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -U ${DB_USER}"
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - awm2024
    restart: unless-stopped
    stop_grace_period: 1m

  awm_django_app:
    image: tcrean15/geodjango_backend:latest
    expose:
      - "8001"
    depends_on:
      postgis:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DJANGO_SETTINGS_MODULE=geodjango_tutorial.settings
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgis
      - DB_PORT=5432
      - REDIS_HOST=redis
      - DJANGO_ALLOWED_HOSTS=*
    networks:
      - awm2024
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    restart: unless-stopped
    stop_grace_period: 1m
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             daphne -b 0.0.0.0 -p 8001 geodjango_tutorial.asgi:application"

networks:
  awm2024:
    name: awm2024
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume: