# Generated by Django 4.2.16 on 2025-01-02 13:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0003_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="kitty_value_per_player",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="game",
            name="total_kitty",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="game",
            name="start_area",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
