# Generated by Django 4.2.16 on 2025-01-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0004_game_kitty_value_per_player_game_total_kitty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="kitty_value_per_player",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name="game",
            name="total_kitty",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
