# Generated by Django 4.2.16 on 2024-12-29 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("world", "0005_remove_game_finished_at_remove_game_next_hint_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameplayer",
            name="team",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="gameplayer",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_players",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
