# Generated by Django 4.2.16 on 2024-12-31 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0006_alter_gameplayer_team_alter_gameplayer_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="next_area_reduction",
        ),
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAITING", "Waiting for players"),
                    ("ACTIVE", "Game in progress"),
                    ("FINISHED", "Game finished"),
                ],
                default="WAITING",
                max_length=20,
            ),
        ),
    ]
