# Generated by Django 4.2.16 on 2024-12-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0007_remove_game_next_area_reduction_alter_game_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="area_set",
            field=models.BooleanField(default=False),
        ),
    ]
