# Generated by Django 4.2.16 on 2024-12-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0008_game_area_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="radius",
            field=models.FloatField(default=500),
        ),
    ]
