# Generated by Django 4.2.16 on 2025-01-01 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0009_add_gameplayer_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameplayer",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
